### ISSUE TITLE
Possible race between vdev removal and pool destruction

### ISSUE THREAD

**Issue by freqlabs** [openzfs/zfs#10534]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version | 13.0-CURRENT
Architecture	| amd64
ZFS Version	| master @ 8a3d9186b

### Describe the problem you're observing
I'm working on some code that tests ZFS ioctls and have found that occasionally the test for vdev removal will panic the system by trying to dereference a null spa->spa_root_vdev pointer in vdev_autotrim_stop_all via spa_vdev_remove_thread. Putting a check for null here only moves the panic to spa_config_enter also via spa_vdev_remove_thread.

### Describe how to reproduce the problem
I am able to reproduce this problem by running my test code in a loop. It only last for a few iterations.
This is only a theory but it seems that destroying the pool immediately after initiating the device removal causes structures to be freed while still in use by the removal.

### Include any warning/errors/backtraces from the system logs

```
Unread portion of the kernel message buffer:
cpuid = 2; apic id = 02
fault virtual address   = 0x80
fault code              = supervisor read data, page not present
instruction pointer     = 0x20:0xffffffff8228e725
stack pointer           = 0x28:0xfffffe022d0619d0
frame pointer           = 0x28:0xfffffe022d061a00
code segment            = base 0x0, limit 0xfffff, type 0x1b
                        = DPL 0, pres 1, long 1, def32 0, gran 1
processor eflags        = interrupt enabled, resume, IOPL = 0
current process         = 54 (solthread 0xfffffff)
trap number             = 12
panic: page fault
cpuid = 2
time = 1593906170
KDB: stack backtrace:
db_trace_self_wrapper() at db_trace_self_wrapper+0x2b/frame 0xfffffe022d061690
vpanic() at vpanic+0x182/frame 0xfffffe022d0616e0
panic() at panic+0x43/frame 0xfffffe022d061740
trap_fatal() at trap_fatal+0x387/frame 0xfffffe022d0617a0
trap_pfault() at trap_pfault+0x4f/frame 0xfffffe022d0617f0
trap() at trap+0x271/frame 0xfffffe022d061900
calltrap() at calltrap+0x8/frame 0xfffffe022d061900
--- trap 0xc, rip = 0xffffffff8228e725, rsp = 0xfffffe022d0619d0, rbp = 0xfffffe022d061a00 ---
vdev_autotrim_stop_all() at vdev_autotrim_stop_all+0x15/frame 0xfffffe022d061a00
spa_vdev_enter() at spa_vdev_enter+0x45/frame 0xfffffe022d061a20
spa_vdev_remove_thread() at spa_vdev_remove_thread+0x147e/frame 0xfffffe022d061bb0
fork_exit() at fork_exit+0x7e/frame 0xfffffe022d061bf0
fork_trampoline() at fork_trampoline+0xe/frame 0xfffffe022d061bf0
--- trap 0, rip = 0, rsp = 0, rbp = 0 ---
KDB: enter: panic
Uptime: 5m13s
```
```
(kgdb) bt
#0  __curthread () at /usr/src/sys/amd64/include/pcpu_aux.h:55
#1  doadump (textdump=1) at /usr/src/sys/kern/kern_shutdown.c:394
#2  0xffffffff80bd9bfb in kern_reboot (howto=260) at /usr/src/sys/kern/kern_shutdown.c:481
#3  0xffffffff80bda07a in vpanic (fmt=<optimized out>, ap=<optimized out>) at /usr/src/sys/kern/kern_shutdown.c:913
#4  0xffffffff80bd9e93 in panic (fmt=<unavailable>) at /usr/src/sys/kern/kern_shutdown.c:839
#5  0xffffffff8106e797 in trap_fatal (frame=0xfffffe022d061910, eva=128) at /usr/src/sys/amd64/amd64/trap.c:919
#6  0xffffffff8106e7ef in trap_pfault (frame=0xfffffe022d061910, usermode=<optimized out>, signo=<optimized out>, ucode=<optimized out>)
    at /usr/src/sys/amd64/amd64/trap.c:736
#7  0xffffffff8106de51 in trap (frame=0xfffffe022d061910) at /usr/src/sys/amd64/amd64/trap.c:400
#8  <signal handler called>
#9  0xffffffff8228e725 in vdev_autotrim_stop_all (spa=0xfffffe01da0df000) at zfs/vdev_trim.c:1473
#10 0xffffffff8220ef45 in spa_vdev_enter (spa=0xfffffe01da0df000) at zfs/spa_misc.c:1163
#11 0xffffffff8228a75e in vdev_remove_complete (spa=<optimized out>) at zfs/vdev_removal.c:1223
#12 spa_vdev_remove_thread (arg=0xfffffe01da0df000) at zfs/vdev_removal.c:1596
#13 0xffffffff80b9838e in fork_exit (callout=0xffffffff822892e0 <spa_restart_removal+240>, arg=0xfffffe01da0df000, frame=0xfffffe022d061c00)
    at /usr/src/sys/kern/kern_fork.c:1052
#14 <signal handler called>
(kgdb) frame 9
#9  0xffffffff8228e725 in vdev_autotrim_stop_all (spa=0xfffffe01da0df000) at zfs/vdev_trim.c:1473
warning: Source file is more recent than executable.
1473
(kgdb) l
1468     */
1469    void
1470    vdev_autotrim_stop_all(spa_t *spa)
1471    {
1472            vdev_t *root_vd = spa->spa_root_vdev;
1473
1474            for (uint64_t i = 0; i < root_vd->vdev_children; i++)
1475                    vdev_autotrim_stop_wait(root_vd->vdev_child[i]);
1476    }
1477
(kgdb) p root_vd
$1 = <optimized out>
(kgdb) p spa->spa_root_vdev
$2 = (vdev_t *) 0x0
(kgdb)
```

After adding a null check:
```
Fatal trap 12: page fault while in kernel mode
cpuid = 24; apic id = 24
fault virtual address   = 0x448
fault code              = supervisor read data, page not present
instruction pointer     = 0x20:0xffffffff80be43b8
stack pointer           = 0x28:0xfffffe0224dfd920
frame pointer           = 0x28:0xfffffe0224dfd9b0
code segment            = base 0x0, limit 0xfffff, type 0x1b
                        = DPL 0, pres 1, long 1, def32 0, gran 1
processor eflags        = interrupt enabled, resume, IOPL = 0
current process         = 54 (solthread 0xfffffff)
trap number             = 12
panic: page fault
cpuid = 24
time = 1593926333
KDB: stack backtrace:
db_trace_self_wrapper() at db_trace_self_wrapper+0x2b/frame 0xfffffe0224dfd5e0
vpanic() at vpanic+0x182/frame 0xfffffe0224dfd630
panic() at panic+0x43/frame 0xfffffe0224dfd690
trap_fatal() at trap_fatal+0x387/frame 0xfffffe0224dfd6f0
trap_pfault() at trap_pfault+0x4f/frame 0xfffffe0224dfd740
trap() at trap+0x271/frame 0xfffffe0224dfd850
calltrap() at calltrap+0x8/frame 0xfffffe0224dfd850
--- trap 0xc, rip = 0xffffffff80be43b8, rsp = 0xfffffe0224dfd920, rbp = 0xfffffe0224dfd9b0 ---
_sx_xlock_hard() at _sx_xlock_hard+0x178/frame 0xfffffe0224dfd9b0
spa_config_enter() at spa_config_enter+0x9b/frame 0xfffffe0224dfda00
spa_vdev_enter() at spa_vdev_enter+0x57/frame 0xfffffe0224dfda20
spa_vdev_remove_thread() at spa_vdev_remove_thread+0x147e/frame 0xfffffe0224dfdbb0
fork_exit() at fork_exit+0x7e/frame 0xfffffe0224dfdbf0
fork_trampoline() at fork_trampoline+0xe/frame 0xfffffe0224dfdbf0
--- trap 0, rip = 0, rsp = 0, rbp = 0 ---
KDB: enter: panic
Uptime: 4m34s
```
```
(kgdb) bt
#0  __curthread () at /usr/src/sys/amd64/include/pcpu_aux.h:55
#1  doadump (textdump=1) at /usr/src/sys/kern/kern_shutdown.c:394
#2  0xffffffff80bd9bfb in kern_reboot (howto=260)
    at /usr/src/sys/kern/kern_shutdown.c:481
#3  0xffffffff80bda07a in vpanic (fmt=<optimized out>, ap=<optimized out>)
    at /usr/src/sys/kern/kern_shutdown.c:913
#4  0xffffffff80bd9e93 in panic (fmt=<unavailable>)
    at /usr/src/sys/kern/kern_shutdown.c:839
#5  0xffffffff8106e797 in trap_fatal (frame=0xfffffe0224dfd860, eva=1096)
    at /usr/src/sys/amd64/amd64/trap.c:919
#6  0xffffffff8106e7ef in trap_pfault (frame=0xfffffe0224dfd860,
    usermode=<optimized out>, signo=<optimized out>, ucode=<optimized out>)
    at /usr/src/sys/amd64/amd64/trap.c:736
#7  0xffffffff8106de51 in trap (frame=0xfffffe0224dfd860)
    at /usr/src/sys/amd64/amd64/trap.c:400
#8  <signal handler called>
#9  _sx_xlock_hard (sx=0xfffffe02435fa560, x=<optimized out>,
    opts=<optimized out>) at /usr/src/sys/kern/kern_sx.c:686
#10 0xffffffff8220d9db in spa_config_enter (spa=0xfffffe02435f9000, locks=127,
    tag=<optimized out>, rw=RW_WRITER) at zfs/spa_misc.c:501
#11 0xffffffff8220f417 in spa_vdev_config_enter (spa=0xfffffe02435f9000)
    at zfs/spa_misc.c:1202
#12 spa_vdev_enter (spa=0xfffffe02435f9000) at zfs/spa_misc.c:1165
#13 0xffffffff8228ac3e in vdev_remove_complete (spa=<optimized out>)
    at zfs/vdev_removal.c:1236
#14 spa_vdev_remove_thread (arg=0xfffffe02435f9000) at zfs/vdev_removal.c:1596
#15 0xffffffff80b9838e in fork_exit (
    callout=0xffffffff822897c0 <spa_vdev_remove_thread>, arg=0xfffffe02435f9000,
    frame=0xfffffe0224dfdc00) at /usr/src/sys/kern/kern_fork.c:1052
#16 <signal handler called>
(kgdb) frame 9
#9  _sx_xlock_hard (sx=0xfffffe02435fa560, x=<optimized out>,
    opts=<optimized out>) at /usr/src/sys/kern/kern_sx.c:686
686                             if (!TD_IS_RUNNING(owner))
(kgdb) p owner
$3 = (volatile struct thread *) 0x0
(kgdb) frame 10
#10 0xffffffff8220d9db in spa_config_enter (spa=0xfffffe02435f9000, locks=127,
    tag=<optimized out>, rw=RW_WRITER) at zfs/spa_misc.c:501
501                     mutex_enter(&scl->scl_lock);
(kgdb) l
496                     spa_config_lock_t *scl = &spa->spa_config_lock[i];
497                     if (scl->scl_writer == curthread)
498                             wlocks_held |= (1 << i);
499                     if (!(locks & (1 << i)))
500                             continue;
501                     mutex_enter(&scl->scl_lock);
502                     if (rw == RW_READER) {
503                             while (scl->scl_writer || scl->scl_write_wanted) {
504                                     cv_wait(&scl->scl_cv, &scl->scl_lock);
505                             }
(kgdb)
```

**Comment by freqlabs** [comment]
This test is now passing on zfs-kmod-2.1.0-FreeBSD_g3522f57b6.
