### ISSUE TITLE
arc_summary | head -> broken pipe

### ISSUE THREAD

**Issue by devZer0** [openzfs/zfs#12036]
Distribution Name	| debian buster / proxmox
Distribution Version	| 10.9
Linux Kernel	| 5.4.106-1-pve
Architecture	| x86_64
ZFS Version	| 2.0.4-pve1
SPL Version	| 2.0.4-pve1

### Describe the problem you're observing

when piping output arc_summary to head util for example, i'm getting weird behaviour

```
# arc_summary |head

------------------------------------------------------------------------
ZFS Subsystem Report                            Wed May 12 22:07:21 2021
Linux 5.4.106-1-pve                                           2.0.4-pve1
Machine: pbs01 (x86_64)                                       2.0.4-pve1

ARC status:                                                      HEALTHY
        Memory throttle count:                                         0

ARC size (current):                                    48.8 %    2.9 GiB
Traceback (most recent call last):
  File "/usr/sbin/arc_summary", line 875, in <module>
    main()
  File "/usr/sbin/arc_summary", line 869, in main
    section_calls[section](kstats)
  File "/usr/sbin/arc_summary", line 756, in section_tunables
    print(format_raw_line(key, value))
BrokenPipeError: [Errno 32] Broken pipe
```

same command another run

```
# arc_summary |head

------------------------------------------------------------------------
ZFS Subsystem Report                            Wed May 12 22:07:23 2021
Linux 5.4.106-1-pve                                           2.0.4-pve1
Machine: pbs01 (x86_64)                                       2.0.4-pve1

ARC status:                                                      HEALTHY
        Memory throttle count:                                         0

ARC size (current):                                    48.8 %    2.9 GiB
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by gdevenyi** [comment]
Just this:
https://linuxpip.org/broken-pipe-python-error/

**Comment by rincebrain** [comment]
Seems like round two of #6965 - maybe the patch for this got lost in the interim.
