### ISSUE TITLE
ztest failure: NULL pointer deref in `vdev_initialize_thread`

### ISSUE THREAD

**Issue by problame** [openzfs/zfs#12128]
I encountered this crash multiple times (but several hours apart) while running `zloop.sh`.

```
git describe 
zfs-2.0.0-rc1-313-g06346cc5b
```

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8d15cfe5fa in zfs_btree_first (tree=tree@entry=0x0, where=where@entry=0x7f8d0ce74be0) at ../../module/zfs/btree.c:1074
1074            if (tree->bt_height == -1) {
[Current thread is 1 (Thread 0x7f8d0ce76700 (LWP 4039825))]
(gdb) bt
#0  0x00007f8d15cfe5fa in zfs_btree_first (tree=tree@entry=0x0, where=where@entry=0x7f8d0ce74be0) at ../../module/zfs/btree.c:1074
#1  0x00007f8d15d96fc6 in range_tree_walk (rt=0x0, func=func@entry=0x7f8d15d953d0 <range_tree_remove>, arg=0x7f8cc403a650)
    at ../../module/zfs/range_tree.c:711
#2  0x00007f8d15d8377f in metaslab_load_impl (msp=0x7f8cc400c510) at ../../module/zfs/metaslab.c:2339
#3  metaslab_load (msp=msp@entry=0x7f8cc400c510) at ../../module/zfs/metaslab.c:2489
#4  0x00007f8d15ddf607 in vdev_initialize_calculate_progress (vd=vd@entry=0x55c7f7157410) at ../../module/zfs/vdev_initialize.c:404
#5  0x00007f8d15ddfb9b in vdev_initialize_thread (arg=0x55c7f7157410) at ../../module/zfs/vdev_initialize.c:519
#6  0x00007f8d15adbea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007f8d15a09def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

[zloop-210526-195422.zip](https://github.com/openzfs/zfs/files/6550124/zloop-210526-195422.zip)

**Comment by problame** [comment]
Can confirm that this has already been fixed in https://github.com/openzfs/zfs/pull/11737
