### ISSUE TITLE
ztest fails in l2arc_apply_transforms comparing calculated MAC

### ISSUE THREAD

**Issue by pcd1193182** [openzfs/zfs#12869]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.04
Kernel Version	| 5.4.0-90
Architecture	| amd64
OpenZFS Version	| 2.1.99 + delphix changes

### Describe the problem you're observing
The specific assertion that failed here is ASSERT0(bcmp(mac, hdr->b_crypt_hdr.b_mac, ZIO_DATA_MAC_LEN));.  This assertion verifies that the calculated MAC is the same as the one stored in the header. Failure here means that when redoing the encryption process in order to store the data in the L2ARC, we somehow got a result that differs from the one we got when retrieving the data as it was stored on disk (I think, anyway). This seems like it might be possible if the data was somehow transformed between how it was stored on disk and its current in-memory state.

 
Examining the ARC header, it looks like the ARC_FLAG_COMPRESSED_ARC flag is set. When examining the compression bits, we see that it looks like the compression mode is ZIO_COMPRESS_OFF. This tracks with the b_psize being equal to the b_lsize (both 32, representing a 16 KiB block).

### Describe how to reproduce the problem
Occasional ztest failure

### Include any warning/errors/backtraces from the system logs
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ff3ef1b5921 in __GI_abort () at abort.c:79
#2  0x00007ff3efd3f805 in libspl_assertf (file=0x7ff3f01ea275 "../../module/zfs/arc.c", func=0x7ff3f01ec910 <__FUNCTION__.20744> "l2arc_apply_transforms", line=9014, format=<optimized out>) at assert.c:45
#3  0x00007ff3effa5f98 in l2arc_apply_transforms (spa=spa@entry=0x555e32d69e90, hdr=hdr@entry=0x7ff3b940d250, asize=asize@entry=16384, abd_out=abd_out@entry=0x7ff3ec399e20) at ../../module/zfs/arc.c:9014
#4  0x00007ff3effb8516 in l2arc_write_buffers (spa=spa@entry=0x555e32d69e90, dev=dev@entry=0x7ff3d444b490, target_sz=target_sz@entry=8388608) at ../../module/zfs/arc.c:9207
#5  0x00007ff3effb9c45 in l2arc_feed_thread (unused=<optimized out>) at ../../module/zfs/arc.c:9425
#6  0x00007ff3ef56d6db in start_thread (arg=0x7ff3ec39b700) at pthread_create.c:463
#7  0x00007ff3ef29671f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I have a core file that I can do some basic analysis on if needed.

**Comment by pcd1193182** [comment]
Issue still occurs
