### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow

### ISSUE THREAD

**Issue by mmaybee** [openzfs/zfs#15177]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.04
Kernel Version	|  5.15.0-67
Architecture	| x86_64
OpenZFS Version	| zfs-2.2.99-1

### Describe the problem you're observing
While running zloop with bits compiled with the address sanitizer enabled, multiple panics occurred due to detection of heap-buffer-overflow by the address sanitizer. This was indicating that we were writing off the end of an allocated buffer. All instances indicated that the issue was in `l2arc_apply_transforms()`. Analysis of the issue points to the likely cause being an incorrect `size` provided to `abd_alloc_for_io()` in this code path:
```
	if (compress != ZIO_COMPRESS_OFF && !HDR_COMPRESSION_ENABLED(hdr)) {
		/*
		 * In some cases, we can wind up with size > asize, so
		 * we need to opt for the larger allocation option here.
		 *
		 * (We also need abd_return_buf_copy in all cases because
		 * it's an ASSERT() to modify the buffer before returning it
		 * with arc_return_buf(), and all the compressors
		 * write things before deciding to fail compression in nearly
		 * every case.)
		 */
		cabd = abd_alloc_for_io(size, ismd);
		tmp = abd_borrow_buf(cabd, size);
```
Note that `size` is provided as the buffer size argument, later in the code we see:
```
		if (psize < asize)
			memset((char *)tmp + psize, 0, asize - psize);
```
This `memset()` call triggers the address sanitizer panic. Note that we are now using `asize` here for the buffer size. In this instance, we have passed in 4096 for `asize`, and `size` has been calculated at 2048. So we attempt to fill 2048 bytes past the end of the allocated buffer with zeros.

### Describe how to reproduce the problem
Given the frequency of the panics observed, this is likely easily reproducible by enabling address sanitation support when building ZFS and running `zloop`.

### Include any warning/errors/backtraces from the system logs

```
==320544==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62501ae8d800 at pc 0x7f988536af3d bp 0x7f983d665bc0 sp 0x7f983d665368
WRITE of size 4047 at 0x62501ae8d800 thread T95
    #0 0x7f988536af3c in __interceptor_memset ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:762
    #1 0x7f9884a477ee in memset /usr/include/x86_64-linux-gnu/bits/string_fortified.h:71
    #2 0x7f9884a477ee in l2arc_apply_transforms ../module/zfs/arc.c:9144
    #3 0x7f9884a69418 in l2arc_write_buffers ../module/zfs/arc.c:9366
    #4 0x7f9884a6bf11 in l2arc_feed_thread ../module/zfs/arc.c:9590
    #5 0x7f98849c87de in zk_thread_wrapper libzpool/kernel.c:90
    #6 0x7f9880de4608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608)
    #7 0x7f9880d09132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132)

0x62501ae8d800 is located 0 bytes to the right of 2048-byte region [0x62501ae8d000,0x62501ae8d800)
allocated by thread T95 here:
    #0 0x7f98854116e5 in __interceptor_posix_memalign ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:217
    #1 0x7f9884d7c565 in umem_alloc_aligned ../lib/libspl/include/umem.h:107
    #2 0x7f9884d7c67c in umem_cache_alloc ../lib/libspl/include/umem.h:198
    #3 0x7f9884a3c174 in abd_alloc_linear ../module/zfs/abd.c:226
    #4 0x7f9884a47195 in l2arc_apply_transforms ../module/zfs/arc.c:9126
    #5 0x7f9884a69418 in l2arc_write_buffers ../module/zfs/arc.c:9366
    #6 0x7f9884a6bf11 in l2arc_feed_thread ../module/zfs/arc.c:9590
    #7 0x7f98849c87de in zk_thread_wrapper libzpool/kernel.c:90
    #8 0x7f9880de4608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608)

Thread T95 created by T0 here:
    #0 0x7f988533d815 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cc:208
    #1 0x7f98849c8d56 in zk_thread_create libzpool/kernel.c:140
    #2 0x7f9884c3e221 in spa_init ../module/zfs/spa_misc.c:2574
    #3 0x7f98849caf73 in kernel_init libzpool/kernel.c:824
    #4 0x558583d6a4e4 in ztest_run cmd/ztest.c:7800
    #5 0x558583d56ffe in main cmd/ztest.c:8405
    #6 0x7f9880c0e082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:762 in __interceptor_memset
Shadow bytes around the buggy address:
  0x0c4a835c9ab0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a835c9ac0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a835c9ad0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a835c9ae0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a835c9af0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c4a835c9b00:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a835c9b10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a835c9b20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a835c9b30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a835c9b40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a835c9b50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==320544==ABORTING
```

**Comment by rincebrain** [comment]
Nasty, when I added that block in 7bf06f7262, I didn't realize sometimes size could wind up being the smaller of the two. This seems like it should have been broken for a long time, though, if that's the flaw...

...hm. I'm not sure what the correct thing to do here is, now, if that's not some other piece of code mangling a header.

**Comment by mmaybee** [comment]
This may have to do with a difference in device record size between the general pool storage and the l2arc device: perhaps we have used 4K for `asize` because the l2arc is a 4K device, but the allocated size for the original data block was only 2K because it was allocated on a 512 device? In any event, it seems like we should be able to choose the largest size between the two for this bit of code. The interface expects an abd buffer of `asize` to be returned here anyway.

I have been playing with a fix and will open a PR shortly for you to take a look at.
