### ISSUE TITLE
arc_summary Error in proxmox

### ISSUE THREAD

**Issue by awptechnologies** [openzfs/zfs#15490]
i have replaced my boot drive by using sgdisk to configure the partitions to match old drive. create zfs snapshot. I then did a send and receive to new pool removed old disk and everything seemed perfect. It booted fine all my vms are there and working. My issue is with arc_summary i get this error:
ZFS Subsystem Report                            Fri Nov 03 13:39:39 2023
Linux 6.2.16-19-pve                                          2.1.13-pve1
Machine: Earth (x86_64)                                      2.1.13-pve1

ARC status:                                                      HEALTHY
        Memory throttle count:                                         0

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/sbin/arc_summary", line 1034, in <module>
    main()
  File "/usr/sbin/arc_summary", line 1028, in main
    section_calls[section](kstats)
  File "/usr/sbin/arc_summary", line 554, in section_arc
    meta = arc_stats['meta']
           ~~~~~~~~~^^^^^^^^
KeyError: 'meta'

Original exception was:
Traceback (most recent call last):
  File "/usr/sbin/arc_summary", line 1034, in <module>
    main()
  File "/usr/sbin/arc_summary", line 1028, in main
    section_calls[section](kstats)
  File "/usr/sbin/arc_summary", line 554, in section_arc
    meta = arc_stats['meta']
           ~~~~~~~~~^^^^^^^^
KeyError: 'meta'


If i run arc_summary -r it prints everything with no problem. Is this something that will be fixed with update or is there something i can do about this issue?

**Comment by amotin** [comment]
It looks like you are trying to run arc_summary from OpenZFS 2.2 on 2.1.13.

**Comment by awptechnologies** [comment]
how do i fix good sir

**Comment by amotin** [comment]
Install user-space and kernel module from the same version.

**Comment by awptechnologies** [comment]
can you help me out with that i ran apt-get install zfs-dkms and did modprobe zfs but its still the same

**Comment by awptechnologies** [comment]
sorry never had to go this in depth with zfs

**Comment by awptechnologies** [comment]
@amotin is this correct

**Comment by awptechnologies** [comment]
Fixed it. I upgraded to 6.5 kernel and it's fixed. Seems like proxmox pushed update for user space before the actually kernel. When I manually installed kernel it worked instantly.  Also I removed zfs-dkms. It didn't seem to need it

**Comment by BrixSat** [comment]
How to install:
    Ensure that either the pve repository is set up correctly.
    You can do so via CLI text-editor or using the web UI under Node -> Repositories

-     apt update
-     apt full-upgrade # to get ZFS 2.2 user space packages
-     apt install pve-kernel-6.5
-     reboot
