### ISSUE TITLE
`zfs destroy` crashes on specific dataset

### ISSUE THREAD

**Issue by 43615** [openzfs/zfs#16798]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| TrueNAS SCALE
Distribution Version	| 24.10.0.2
Kernel Version	| 6.6.44-production+truenas
Architecture	| x86_64
OpenZFS Version	| zfs-2.2.99-1

### Describe the problem you're observing
I'm trying to delete a dataset that was automatically created for the Plex app by TrueNAS and didn't get deleted when uninstalling it:
```
# zfs list -r sto/ix-apps/app_mounts/plex
NAME                                 USED  AVAIL  REFER  MOUNTPOINT
sto/ix-apps/app_mounts/plex         2.35M  57.4T   153K  /mnt/.ix-apps/app_mounts/plex
sto/ix-apps/app_mounts/plex/config  2.10M  57.4T  1.92M  /mnt/.ix-apps/app_mounts/plex/config
```
This happens when running the destroy command:
```
# zfs destroy -Rv sto/ix-apps/app_mounts/plex
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-17_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-18_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-08_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-07_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-20_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-10_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-19_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-16_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-06_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-09_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-11_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-21_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-22_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-12_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-15_00-00-00
will destroy sto/ix-apps/app_mounts/plex/config@daily-2024-11-05_00-00-00
Aborted (core dumped)
```
The utility exits with code 134, and nothing is actually deleted. I have used the same command on other datasets with no issues.

I also can't `rm -rf` the files at the mountpoint, it says "Device or resource busy".

### Describe how to reproduce the problem
Don't know the specific circumstances, just trying to delete a dataset.

### Include any warning/errors/backtraces from the system logs
Core dump (recompressed as ZIP):
[core.zfs.0.d9082b294cf042da963c2e5571dcc027.716503.1732278964000000.zip](https://github.com/user-attachments/files/17870191/core.zfs.0.d9082b294cf042da963c2e5571dcc027.716503.1732278964000000.zip)

**Comment by 43615** [comment]
I was able to delete the `config` directory after unmounting the dataset, but I still can't delete the dataset. Attempting `zfs rename` and `zfs set mountpoint=none` results in the same crash.

**Comment by asomers** [comment]
The binary core dump isn't very useful to people who don't have the exact same build as you.  Better would be if you could post the stack trace of the crash.  Do you have that?

**Comment by 43615** [comment]
Thanks for caring about this!

I don't know how to make a stack trace, could you please tell me? Keep in mind that this is a very appliance-y OS, so I wouldn't feel great about modifying the executables (if that's required).

And FWIW, I now believe that the dataset corruption was most likely caused by the system drive being on a faulty storage controller, resulting in a utility binary working incorrectly. I have since replaced the storage controller and done a clean reinstall of TrueNAS. Still, the utilities should be able to handle such corruption and discard the dataset.

Some new behavior in the current state: Scrubbing the pool reveals checksum errors on 4 out of 6 drives (pool is a RAID-Z1) and indeed shows the directories in question as being affected. It does not fix the corruption. I have tried replacing the drives one by one with a spare, but the checksum errors reappear anyway.

I understand that the only "proper" solution is to copy my healthy data to a temporary location, then destroy and recreate the pool. However, I currently don't have the means to get the required amount of additional storage. If there is a "dirty' way to unlink (?) the dataset, please let me know.

**Comment by asomers** [comment]
Do make a stack trace, do `gdb /sbin/zfs /path/to/core.zfs.0` and then at the prompt do `bt`.

**Comment by 43615** [comment]
Did it with coredumpctl:
```
# coredumpctl debug 2353105
           PID: 2353105 (zfs)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 6 (ABRT)
     Timestamp: Sat 2025-04-12 02:48:01 CEST (15min ago)
  Command Line: zfs destroy -Rv sto/ix-apps/app_mounts/plex
    Executable: /usr/sbin/zfs
 Control Group: /system.slice/ssh.service
          Unit: ssh.service
         Slice: system.slice
       Boot ID: ad781dd0c68b4c1984fbffb335310c0a
    Machine ID: 541c496a601b4680af26a62b86e025ba
      Hostname: keepstar
       Storage: /var/lib/systemd/coredump/core.zfs.0.ad781dd0c68b4c1984fbffb335310c0a.2353105.1744418881000000.zst (present)
  Size on Disk: 184.7K
       Message: Process 2353105 (zfs) of user 0 dumped core.
                
                Module libudev.so.1 from deb systemd-252.26-1~deb12u2.amd64
                Stack trace of thread 2353105:
                #0  0x00007f1008f39e2c n/a (libc.so.6 + 0x8ae2c)
                #1  0x00007f1008eeafb2 raise (libc.so.6 + 0x3bfb2)
                #2  0x00007f1008ed5472 abort (libc.so.6 + 0x26472)
                #3  0x00007f10090df6c5 n/a (libzfs.so.4 + 0x156c5)
                #4  0x00007f10090e5e1a n/a (libzfs.so.4 + 0x1be1a)
                #5  0x00007f10090f117b zfs_iter_snapshots_v2 (libzfs.so.4 + 0x2717b)
                #6  0x00007f10090f1447 n/a (libzfs.so.4 + 0x27447)
                #7  0x00007f10090f0fa6 zfs_iter_filesystems_v2 (libzfs.so.4 + 0x26fa6)
                #8  0x00007f10090f1332 n/a (libzfs.so.4 + 0x27332)
                #9  0x00007f10090f1b65 zfs_iter_dependents_v2 (libzfs.so.4 + 0x27b65)
                #10 0x000055861c963248 n/a (zfs + 0xf248)
                #11 0x000055861c95b412 n/a (zfs + 0x7412)
                #12 0x00007f1008ed624a n/a (libc.so.6 + 0x2724a)
                #13 0x00007f1008ed6305 __libc_start_main (libc.so.6 + 0x27305)
                #14 0x000055861c95b551 n/a (zfs + 0x7551)
                ELF object binary architecture: AMD x86-64

GNU gdb (Debian 13.1-3) 13.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/zfs...
(No debugging symbols found in /usr/sbin/zfs)
[New LWP 2353105]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `zfs destroy -Rv sto/ix-apps/app_mounts/plex'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1008f39e2c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f1008f39e2c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f1008eeafb2 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f1008ed5472 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f10090df6c5 in ?? () from /lib/x86_64-linux-gnu/libzfs.so.4
#4  0x00007f10090e5e1a in ?? () from /lib/x86_64-linux-gnu/libzfs.so.4
#5  0x00007f10090f117b in zfs_iter_snapshots_v2 () from /lib/x86_64-linux-gnu/libzfs.so.4
#6  0x00007f10090f1447 in ?? () from /lib/x86_64-linux-gnu/libzfs.so.4
#7  0x00007f10090f0fa6 in zfs_iter_filesystems_v2 () from /lib/x86_64-linux-gnu/libzfs.so.4
#8  0x00007f10090f1332 in ?? () from /lib/x86_64-linux-gnu/libzfs.so.4
#9  0x00007f10090f1b65 in zfs_iter_dependents_v2 () from /lib/x86_64-linux-gnu/libzfs.so.4
#10 0x000055861c963248 in ?? ()
#11 0x000055861c95b412 in ?? ()
#12 0x00007f1008ed624a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#13 0x00007f1008ed6305 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#14 0x000055861c95b551 in ?? ()
```
