### ISSUE TITLE
Odd Behavior importing OmniOS pool with L2Arc

### ISSUE THREAD

**Issue by dave-fl** [openzfs/zfs#5554]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Debian
Distribution Version    |  Stable with jessie backports
Linux Kernel                 |   3.16.0-4-amd64
Architecture                 | 
ZFS Version                  |  0.6.5.8-2~bpo8+1
SPL Version                  |  0.6.5.8-2~bpo8+1

### Describe the problem you're observing

zpool import is stating status as "One or more devices contains corrupted data." when pool is fine.  Pool was originally created on OmniOS.  Error is not displayed if L2Arc is removed.

### Describe how to reproduce the problem

1. Export Pool 
2. Import pool on Linux
3. Error will show
4. If above steps are repeated but L2Arc is removed prior to doing so then no error.
5. If using `zpool import -d /dev/disk/by-id/` the correct device is shown but system still believes pool has corrupted data.
6. In example below storage1 is OmniOS, storage2 is Debian.

        root@storage1:/root# zpool status
          pool: main
         state: ONLINE
          scan: scrub repaired 0 in 4h19m with 0 errors on Mon Jan  2 07:19:05 2017
        config:

                NAME                       STATE     READ WRITE CKSUM
                main                       ONLINE       0     0     0
                  mirror-0                 ONLINE       0     0     0
                    c3t50014EE0040F7ABBd0  ONLINE       0     0     0
                    c3t50014EE0AEBA43E8d0  ONLINE       0     0     0
                logs
                  c3t55CD2E404C007405d0    ONLINE       0     0     0
                cache
                  c3t55CD2E404B7D75C2d0    ONLINE       0     0     0

        errors: No known data errors
        root@storage1:/root# zpool export main

        root@storage2:~# zpool import
           pool: main
             id: 16726137309503869186
          state: ONLINE
         status: One or more devices contains corrupted data.
         action: The pool can be imported using its name or numeric identifier.
           see: http://zfsonlinux.org/msg/ZFS-8000-4J
         config:

                main                       ONLINE
                  mirror-0                 ONLINE
                    sdd                    ONLINE
                    sdc                    ONLINE
                cache
                  c3t55CD2E404B7D75C2d0s0
                logs
                  sde                      ONLINE

        root@storage1:/root# zpool remove main c3t55CD2E404B7D75C2d0
        root@storage1:/root# zpool status main
          pool: main
         state: ONLINE
          scan: scrub repaired 0 in 4h19m with 0 errors on Mon Jan  2 07:19:05 2017
        config:

                NAME                       STATE     READ WRITE CKSUM
                main                       ONLINE       0     0     0
                  mirror-0                 ONLINE       0     0     0
                    c3t50014EE0040F7ABBd0  ONLINE       0     0     0
                    c3t50014EE0AEBA43E8d0  ONLINE       0     0     0
                logs
                  c3t55CD2E404C007405d0    ONLINE       0     0     0

        errors: No known data errors
        root@storage1:/root# zpool export main

        root@storage2:~# zpool import
           pool: main
             id: 16726137309503869186
          state: ONLINE
         action: The pool can be imported using its name or numeric identifier.
         config:

                main        ONLINE
                  mirror-0  ONLINE
                    sdd     ONLINE
                    sdc     ONLINE
                logs
                  sde       ONLINE

**Comment by loli10K** [comment]
I don't think there's any corruption going on here, it's just the l2arc device "/dev/dsk/..." that cannot be found when importing the pool.

From the userland debugger we can verify that the vdev state reported by the kernel is a generic `VDEV_STATE_CANT_OPEN`, which results in `ZPOOL_STATUS_CORRUPT_LABEL_R` being returned by `check_status()`:

```
root@debian-8-zfs:~# cat > gdbcmds <<EOF
> set pagination off
> set breakpoint pending on
> b vdev_broken if state != VDEV_STATE_HEALTHY
> b zpool_import_status
> file zpool
> run import -d /dev/disk/by-id
> EOF
root@debian-8-zfs:~# gdb -q -x gdbcmds
No symbol table is loaded.  Use the "file" command.
Breakpoint 1 (vdev_broken if state != VDEV_STATE_HEALTHY) pending.
No symbol table is loaded.  Use the "file" command.
Breakpoint 2 (zpool_import_status) pending.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5dc1700 (LWP 2548)]
[New Thread 0x7ffff5d80700 (LWP 2549)]
[New Thread 0x7ffff5d3f700 (LWP 2550)]
[New Thread 0x7ffff5cfe700 (LWP 2551)]
[Thread 0x7ffff5dc1700 (LWP 2548) exited]
[Thread 0x7ffff5cfe700 (LWP 2551) exited]
[Thread 0x7ffff5d3f700 (LWP 2550) exited]
[Thread 0x7ffff5d80700 (LWP 2549) exited]

Thread 1 "zpool" hit Breakpoint 2, zpool_import_status (config=config@entry=0x627ad0, msgid=msgid@entry=0x7fffffffaaf8, errata=errata@entry=0x7fffffffaaa8) at libzfs_status.c:388
388	{
(gdb) bt
#0  zpool_import_status (config=config@entry=0x627ad0, msgid=msgid@entry=0x7fffffffaaf8, errata=errata@entry=0x7fffffffaaa8) at libzfs_status.c:388
#1  0x000000000040bd7b in show_import (config=0x627ad0) at zpool_main.c:1859
#2  zpool_do_import (argc=<optimized out>, argv=<optimized out>) at zpool_main.c:2531
#3  0x00000000004056fd in main (argc=4, argv=0x7fffffffecc8) at zpool_main.c:7510
(gdb) c
Continuing.

Thread 1 "zpool" hit Breakpoint 1, vdev_broken (state=4, aux=0, errs=0) at libzfs_status.c:101
101		return (state == VDEV_STATE_CANT_OPEN);
(gdb) p state
$1 = 4
(gdb) p/d VDEV_STATE_CANT_OPEN
$2 = 4
(gdb) fin
Run till exit from #0  vdev_broken (state=4, aux=0, errs=0) at libzfs_status.c:101
0x00007ffff7123d33 in find_vdev_problem (vdev=0x6333c0, func=0x7ffff7123a80 <vdev_broken>) at libzfs_status.c:148
148			if (func(vs->vs_state, vs->vs_aux,
Value returned is $3 = 1
(gdb) 
Run till exit from #0  0x00007ffff7123d33 in find_vdev_problem (vdev=0x6333c0, func=0x7ffff7123a80 <vdev_broken>) at libzfs_status.c:148
0x00007ffff7123d88 in find_vdev_problem (vdev=0x6271f0, func=0x7ffff7123a80 <vdev_broken>) at libzfs_status.c:161
161				if (find_vdev_problem(child[c], func))
Value returned is $4 = B_TRUE
(gdb) 
Run till exit from #0  0x00007ffff7123d88 in find_vdev_problem (vdev=0x6271f0, func=0x7ffff7123a80 <vdev_broken>) at libzfs_status.c:161
0x00007ffff7123ff9 in check_status (config=config@entry=0x627ad0, isimport=isimport@entry=B_TRUE, erratap=erratap@entry=0x7fffffffaaa8) at libzfs_status.c:310
310		if (find_vdev_problem(nvroot, vdev_broken))
Value returned is $5 = B_TRUE
(gdb) 
Run till exit from #0  0x00007ffff7123ff9 in check_status (config=config@entry=0x627ad0, isimport=isimport@entry=B_TRUE, erratap=erratap@entry=0x7fffffffaaa8) at libzfs_status.c:310
zpool_import_status (config=config@entry=0x627ad0, msgid=msgid@entry=0x7fffffffaaf8, errata=errata@entry=0x7fffffffaaa8) at libzfs_status.c:391
391		if (ret >= NMSGID)
Value returned is $6 = ZPOOL_STATUS_CORRUPT_LABEL_R
(gdb) list
386	zpool_status_t
387	zpool_import_status(nvlist_t *config, char **msgid, zpool_errata_t *errata)
388	{
389		zpool_status_t ret = check_status(config, B_TRUE, errata);
390	
391		if (ret >= NMSGID)
392			*msgid = NULL;
393		else
394			*msgid = zfs_msgid_table[ret];
395	
(gdb) n
394			*msgid = zfs_msgid_table[ret];
(gdb) 
397	}
(gdb) p *msgid
$7 = 0x7ffff7131f82 "ZFS-8000-4J"
(gdb) c
Continuing.
   pool: testpool
     id: 9299648319758848265
  state: ONLINE
 status: One or more devices contains corrupted data.
 action: The pool can be imported using its name or numeric identifier.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
 config:

	testpool                                    ONLINE
	  usb-QEMU_QEMU_HARDDISK_1-0000:05.7-2-0:0  ONLINE
	cache
	  usb-QEMU_QEMU_HARDDISK_1-0000:05.7-1-0:0
[Inferior 1 (process 2544) exited normally]
(gdb) 
```

From the kernel debugger we can verify the issue is caused by `vdev_disk_open(/dev/dsk/...)` returning ENOENT in `spa_load_impl()`->`spa_load_l2cache()`->`vdev_open()`:

```
Thread 494 hit Breakpoint 2, vdev_set_state (vd=0xffff88002abc7000, isopen=B_TRUE, state=VDEV_STATE_CANT_OPEN, aux=VDEV_AUX_NONE) at /usr/src/zfs/module/zfs/vdev.c:3150
3150	{
(gdb) bt
#0  vdev_set_state (vd=0xffff88002abc7000, isopen=B_TRUE, state=VDEV_STATE_CANT_OPEN, aux=VDEV_AUX_NONE) at /usr/src/zfs/module/zfs/vdev.c:3150
#1  0xffffffffc0471b51 in vdev_open (vd=0xffff88002abc7000) at /usr/src/zfs/module/zfs/vdev.c:1223
#2  0xffffffffc0459972 in spa_load_l2cache (spa=0xffff8800c2f98000) at /usr/src/zfs/module/zfs/spa.c:1570
#3  0xffffffffc045eedd in spa_load_impl (pool_guid=<optimized out>, ereport=<optimized out>, mosconfig=<optimized out>, type=<optimized out>, state=<optimized out>, config=<optimized out>, spa=<optimized out>)
    at /usr/src/zfs/module/zfs/spa.c:2688
#4  spa_load (spa=0xffff8800c2f98000, state=SPA_LOAD_TRYIMPORT, type=<optimized out>, mosconfig=<optimized out>) at /usr/src/zfs/module/zfs/spa.c:2206
#5  0xffffffffc04604b8 in spa_tryimport (tryconfig=<optimized out>) at /usr/src/zfs/module/zfs/spa.c:4077
#6  0xffffffffc048ffbe in zfs_ioc_pool_tryimport (zc=0xffff8800cfe74000) at /usr/src/zfs/module/zfs/zfs_ioctl.c:1626
#7  0xffffffffc049275a in zfsdev_ioctl (filp=<optimized out>, cmd=<optimized out>, arg=140733200032480) at /usr/src/zfs/module/zfs/zfs_ioctl.c:5892
#8  0xffffffff812086f9 in vfs_ioctl (arg=<optimized out>, cmd=<optimized out>, filp=<optimized out>) at fs/ioctl.c:43
#9  do_vfs_ioctl (filp=0xffff880115ac4500, fd=<optimized out>, cmd=<optimized out>, arg=0) at fs/ioctl.c:674
#10 0xffffffff81208ca6 in SYSC_ioctl (arg=<optimized out>, cmd=<optimized out>, fd=<optimized out>) at fs/ioctl.c:689
#11 SyS_ioctl (fd=3, cmd=23046, arg=140733200032480) at fs/ioctl.c:680
#12 0xffffffff815cc1b6 in entry_SYSCALL_64 () at arch/x86/entry/entry_64.S:211
(gdb) fra 1
#1  0xffffffffc0471b51 in vdev_open (vd=0xffff88002abc7000) at /usr/src/zfs/module/zfs/vdev.c:1223
1223			vdev_set_state(vd, B_TRUE, VDEV_STATE_CANT_OPEN,
(gdb) list
1218		if (error) {
1219			if (vd->vdev_removed &&
1220			    vd->vdev_stat.vs_aux != VDEV_AUX_OPEN_FAILED)
1221				vd->vdev_removed = B_FALSE;
1222	
1223			vdev_set_state(vd, B_TRUE, VDEV_STATE_CANT_OPEN,
1224			    vd->vdev_stat.vs_aux);
1225			return (error);
1226		}
1227	
(gdb) p error
$1 = 2
(gdb) p vd->vdev_ops->vdev_op_open
$2 = (vdev_open_func_t *) 0xffffffffc0474000 <vdev_disk_open>
(gdb) p vd->vdev_path
$3 = 0xffff8800be1d9b40 "/dev/dsk/c2t0d0s0"
```

To quickly verify it without a debugger:

```
root@debian-8-zfs:~# echo 1 > /sys/module/zfs/parameters/zfs_dbgmsg_enable
root@debian-8-zfs:~# zpool import -d /dev/disk/by-id
   pool: testpool
     id: 9299648319758848265
  state: ONLINE
 status: One or more devices contains corrupted data.
 action: The pool can be imported using its name or numeric identifier.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
 config:

	testpool                                    ONLINE
	  usb-QEMU_QEMU_HARDDISK_1-0000:05.7-2-0:0  ONLINE
	cache
	  usb-QEMU_QEMU_HARDDISK_1-0000:05.7-1-0:0
root@debian-8-zfs:~# cat /proc/spl/kstat/zfs/dbgmsg
8 0 0x01 -1 0 5197231036 228585690910
timestamp    message 
1489431836   failed open v->vdev_path=/dev/dsk/c2t0d0s0, error=2 count=50
1489431837   failed open v->vdev_path=/dev/dsk/c2t0d0s0, error=2 count=50
```

We can actually feed a symlink to `vdev_disk_open()` to "bypass" the issue:

```
root@debian-8-zfs:~# zpool import
   pool: testpool
     id: 9299648319758848265
  state: ONLINE
 status: One or more devices contains corrupted data.
 action: The pool can be imported using its name or numeric identifier.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
 config:

	testpool    ONLINE
	  sdc       ONLINE
	cache
	  c2t0d0s0
root@debian-8-zfs:~# mkdir /dev/dsk
root@debian-8-zfs:~# ln -s /dev/sdb1 /dev/dsk/c2t0d0s0
root@debian-8-zfs:~# echo 1 > /sys/module/zfs/parameters/zfs_dbgmsg_enable
root@debian-8-zfs:~# zpool import
   pool: testpool
     id: 9299648319758848265
  state: ONLINE
 status: Some supported features are not enabled on the pool.
 action: The pool can be imported using its name or numeric identifier, though
	some features will not be available without an explicit 'zpool upgrade'.
 config:

	testpool    ONLINE
	  sdc       ONLINE
	cache
	  c2t0d0s0
root@debian-8-zfs:~# cat /proc/spl/kstat/zfs/dbgmsg
root@debian-8-zfs:~# 
```
 
Here's the l2arc config saved in the MOS:

```
root@debian-8-zfs:~# zdb -dddd testpool 44
Dataset mos [META], ID 0, cr_txg 4, 78.0K, 47 objects, rootbp DVA[0]=<0:2008c00:200> DVA[1]=<0:8008c00:200> DVA[2]=<0:e008c00:200> [L0 DMU objset] fletcher4 lz4 LE contiguous unique triple size=800L/200P birth=53L/53P fill=47 cksum=bd6cabf5d:4a37a4c12e7:eef5992feab9:20e5f0bead374a

    Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
        44    1    16K    16K  1.50K     512    16K  100.00  packed nvlist
                                                 8   bonus  packed nvlist size
	dnode flags: USED_BYTES 
	dnode maxblkid: 0
        l2cache[0]:
            type: 'disk'
            guid: 877045696208309245
            path: '/dev/dsk/c2t0d0s0'
            devid: 'id1,sd@f4827075458c6ec0b000df8000005/a'
            phys_path: '/pci@0,0/pci1af4,1100@5,7/storage@1/disk@0,0:a'
            whole_disk: 1

```

This should (hopefully) be handled in a better way once we get persistent l2arc.
