### ISSUE TITLE
spa_sync_deferred_frees still dirties dnodes even when there's no work to do

### ISSUE THREAD

**Issue by nwf** [openzfs/zfs#8170]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	|  Debian
Distribution Version	|  9.6
Linux Kernel	|  4.17.8-1
Architecture	|  x86_64
ZFS Version	|  c40a1124e1d1010b665909ad31d2904630018f6f-dirty
### Describe the problem you're observing

During a (userland, in-order) scrub of an otherwise idle pool,
`spa_sync_deferred_frees` continues to dirty dnodes and cause
allocation and write traffic to the disk unnecessarily.

It can be caught in the act by breaking on `dnode_setdirty`:
```
(gdb) bt                              
#0  dnode_setdirty (dn=0x55fac64d6b50, tx=0x7fc367e2cf40) at ../../module/zfs/dnode.c:1622
#1  0x00007fc56bcf4322 in dnode_free_range (dn=0x55fac64d6b50, off=<optimized out>, off@entry=0, len=<optimized out>, len@entry=18446744073709551615, tx=tx@entry=0x7fc367e2cf40) at ../../module/zfs/dnode.c:2161
#2  0x00007fc56bcdd4cd in dmu_free_range (os=<optimized out>, object=<optimized out>, offset=offset@entry=0, size=size@entry=18446744073709551615, tx=tx@entry=0x7fc367e2cf40) at ../../module/zfs/dmu.c:926                                             
#3  0x00007fc56bcd0b41 in bpobj_iterate_impl (bpo=bpo@entry=0x55fac63fb110, func=func@entry=0x7fc56bd2dac0 <spa_free_sync_cb>, arg=arg@entry=0x7fc3cde69800, tx=tx@entry=0x7fc367e2cf40, free=free@entry=B_TRUE) at ../../module/zfs/bpobj.c:267
#4  0x00007fc56bcd0c6b in bpobj_iterate (bpo=bpo@entry=0x55fac63fb110, func=func@entry=0x7fc56bd2dac0 <spa_free_sync_cb>, arg=arg@entry=0x7fc3cde69800, tx=tx@entry=0x7fc367e2cf40) at ../../module/zfs/bpobj.c:368
#5  0x00007fc56bd3275d in spa_sync_deferred_frees (tx=0x7fc367e2cf40, spa=0x55fac63fabd0) at ../../module/zfs/spa.c:7162
#6  spa_sync (spa=spa@entry=0x55fac63fabd0, txg=txg@entry=10377492) at ../../module/zfs/spa.c:7875
#7  0x00007fc56bd4408f in txg_sync_thread (arg=0x55fac67fa410) at ../../module/zfs/txg.c:573
#8  0x00007fc56b81ff2a in start_thread (arg=0x7fc556eda700) at pthread_create.c:463
#9  0x00007fc56b752edf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95    
```
but we can verify that there is no work to be done:
```
(gdb) p ((dsl_dir_phys_t *)(tx->tx_pool->dp_free_dir->dd_dbuf->db_data))->dd_used_bytes
$10 = 0  
```

We can also verify that this does cause write traffic to the disk with `btrace` (and can verify that it is
causing allocation by observing the offsets steadily increase):

```
253,11   7       30     0.918934854 14273  C   R 879922656 + 256 [0]              --- scrub read
253,11   0       24     0.980570164 14273  C   R 5537877288 + 8 [0]               --- some MOS update reads
[...]
253,11   1       45     1.041462133  3844  C  WS 5571355856 + 8 [0]               --- many MOS update writes
[...]
253,11   1       83     1.045284867  3844  C  WS 5671899032 + 8 [0]               --- end of MOS update writes
253,11   4       21     1.125207885 17379  C FWS 0 [0]
253,11   0      131     1.131988751     0  C  WS 376 + 8 [0]                       --- pool sync writes
253,11   0      132     1.132237922     0  C  WS 888 + 8 [0]
253,11   0      133     1.132283012 19382  C  WS 9767535992 + 8 [0]
253,11   0      134     1.132490142 19382  C  WS 9767536504 + 8 [0]
253,11   0      135     1.171118009     0  C FWS 0 [0]
```

It looks like the `dmu_free_range` taken in `bpobj_iterate_impl`
https://github.com/openzfs/zfs/blob/99741bde59d1d1df0963009bb624ddc105f7d8dc/module/zfs/bpobj.c#L347
is spurious and inducing unnecessary work in the case that
`bpo->bpo_phys->bpo_num_blkptrs` is 0.  However, that's frighteningly
generic code, so it may be simpler to have `spa_sync_deferred_frees`
simply return early if there is no work to be done.

**Comment by nwf** [comment]
So far as I know, this is still an issue?
