### ISSUE TITLE
BoltDB (containerd) failing to mmap Docker statedb over ZFS

### ISSUE THREAD

**Issue by sempervictus** [openzfs/zfs#8224]
### System information

 --- | --- 
Distribution Name	|  Arch
Distribution Version	| Current
Linux Kernel	|  4.14
Architecture	| amd64
ZFS Version	| 0.7.12
SPL Version	| 0.7.12

### Describe the problem you're observing

Containerd fails to start when running over ZFS, with the trace apparently indicating an mmap issue with the docker state DB.

### Describe how to reproduce the problem

1. Create an LXC container on top of a ZFS dataset containing ubuntu 16.
2. Deploy securityonion (master mode) into the LXC container and complete configuration (will install docker containers, containerd.io, docker-ce, etc). Run _soup_ to ensure latest package versions are deployed.
3. Stop the docker service, try to start it again.

### Include any warning/errors/backtraces from the system logs

From _journalctl -xe -u containerd_:
```
Dec 23 07:51:49 containerd[10083]: panic: invalid page type: 8030604429271643239: 6570
Dec 23 07:51:49 containerd[10083]: goroutine 1 [running]:
Dec 23 07:51:49 containerd[10083]: github.com/containerd/containerd/vendor/go.etcd.io/bbolt.(*Cursor).search(0xc42050b298, 0xc42050b398, 0x2, 0x20, 0x1b)
Dec 23 07:51:49 containerd[10083]:         /go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/cursor.go:250 +0x38a
Dec 23 07:51:49 containerd[10083]: github.com/containerd/containerd/vendor/go.etcd.io/bbolt.(*Cursor).seek(0xc42050b298, 0xc42050b398, 0x2, 0x20, 0x0, 0x0, 0x2f6528fe680, 0x2f6530d7880, 0x0, 0x0, ...)
Dec 23 07:51:49 containerd[10083]:         /go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/cursor.go:159 +0xa7
Dec 23 07:51:49 containerd[10083]: github.com/containerd/containerd/vendor/go.etcd.io/bbolt.(*Bucket).Bucket(0xc420424018, 0xc42050b398, 0x2, 0x20, 0xc42050b398)
Dec 23 07:51:49 containerd[10083]:         /go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/bucket.go:105 +0xe0
Dec 23 07:51:49 containerd[10083]: github.com/containerd/containerd/vendor/go.etcd.io/bbolt.(*Tx).Bucket(0xc420424000, 0xc42050b398, 0x2, 0x20, 0x2)
Dec 23 07:51:49 containerd[10083]:         /go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/tx.go:101 +0x51
Dec 23 07:51:49 containerd[10083]: github.com/containerd/containerd/metadata.(*DB).Init.func1(0xc420424000, 0x2f6528daf68, 0xc420424000)
Dec 23 07:51:49 containerd[10083]:         /go/src/github.com/containerd/containerd/metadata/db.go:121 +0x174
Dec 23 07:51:49 containerd[10083]: github.com/containerd/containerd/vendor/go.etcd.io/bbolt.(*DB).Update(0xc420422000, 0xc42050b520, 0x0, 0x0)
Dec 23 07:51:49 containerd[10083]:         /go/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/db.go:670 +0x92
Dec 23 07:51:49 containerd[10083]: github.com/containerd/containerd/metadata.(*DB).Init(0xc4203a26c0, 0x2f6528ff040, 0xc42003c018, 0xc42050b640, 0xc4203a26c0)
Dec 23 07:51:49 containerd[10083]:         /go/src/github.com/containerd/containerd/metadata/db.go:103 +0xb1
Dec 23 07:51:49 containerd[10083]: github.com/containerd/containerd/services/server.LoadPlugins.func2(0xc42036aa80, 0x2f652080c31, 0xf, 0xc42024f060, 0x1e)
Dec 23 07:51:49 containerd[10083]:         /go/src/github.com/containerd/containerd/services/server/server.go:269 +0x53f
Dec 23 07:51:49 containerd[10083]: github.com/containerd/containerd/plugin.(*Registration).Init(0xc4203a6550, 0xc42036aa80, 0xc4203a6550)
Dec 23 07:51:49 containerd[10083]:         /go/src/github.com/containerd/containerd/plugin/plugin.go:100 +0x3a
Dec 23 07:51:49 containerd[10083]: github.com/containerd/containerd/services/server.New(0x2f6528ff040, 0xc42003c018, 0xc4200f2000, 0x1, 0xc42050bc80, 0x0)
Dec 23 07:51:49 containerd[10083]:         /go/src/github.com/containerd/containerd/services/server/server.go:120 +0x557
Dec 23 07:51:49 containerd[10083]: github.com/containerd/containerd/cmd/containerd/command.App.func1(0xc4200e8000, 0xc4200e8000, 0xc42050bd07)
Dec 23 07:51:49 containerd[10083]:         /go/src/github.com/containerd/containerd/cmd/containerd/command/main.go:141 +0x67e
Dec 23 07:51:49 containerd[10083]: github.com/containerd/containerd/vendor/github.com/urfave/cli.HandleAction(0x2f6526bff40, 0x2f6528d9360, 0xc4200e8000, 0xc4202d6120, 0x0)
Dec 23 07:51:49 containerd[10083]:         /go/src/github.com/containerd/containerd/vendor/github.com/urfave/cli/app.go:502 +0xca
Dec 23 07:51:49 containerd[10083]: github.com/containerd/containerd/vendor/github.com/urfave/cli.(*App).Run(0xc4202c8000, 0xc42003a1b0, 0x1, 0x1, 0x0, 0x0)
Dec 23 07:51:49 containerd[10083]:         /go/src/github.com/containerd/containerd/vendor/github.com/urfave/cli/app.go:268 +0x60e
Dec 23 07:51:49 containerd[10083]: main.main()
Dec 23 07:51:49 containerd[10083]:         github.com/containerd/containerd/cmd/containerd/main.go:33 +0x51
```

**Comment by devZer0** [comment]
just for better understanding , what in detail is indicating that it's an mmap issue with the docker state db and what makes you sure that it relates to zfs ?
