### ISSUE TITLE
zfs resumable send|recv complains about embedded data with encryption when not using encryption

### ISSUE THREAD

**Issue by jmesmon** [openzfs/zfs#8886]
### System information

Type | Version/Name dest (recv) | src (send)
 --- | --- | ----
Distribution Name	| Gentoo | ArchLinux
Linux Kernel	| 5.1.8 | 5.1.5
Architecture	| x86_64 | x86_64
ZFS Version	| 0.8.0-r1-gentoo | 0.8.0-1

### Describe the problem you're observing

After performing a number of incremental `send|recv`s between 2 hosts, the recvs for a particular dataset is failing with `cannot receive new filesystem stream: incompatible embedded data stream feature with encrypted receive.`. No zfs encryption is used on either pool (src or dst).

Resuming these failed `send|recv`s sometimes functions, but then the next incremental recv fails in the same manner. Eventually, the resume itself began to fail with the same error message as above.

At this point I examined the dataset and attempted to abort the recv, only to be told by `zfs receive -A` that their was no resumable receive state despite the `receive_resume_token` property having a value. (full command & output below).

I looked through other tickets, and #8801 appears similar in the inability to abort, but the process to get to that point appears different.

### Log outputs

This first bit is extracted from some of my backup logs, and the resume token is slightly truncated. It also doesn't explicitly show the piping between commands, you'll see the `send` and `recv` one after another.

This first bit is the first failure I've seen in my logs, which _appears_ to have triggered the fallback to using the resume
```
Jun 09 20:53:44 arnold zoop[144785]: run: "ssh" "gun-zxfer" "zfs" "send" "-eLc" "innerpool/ROOT/arch@znap_2019-04-01-0400_monthly"
Jun 09 20:53:44 arnold zoop[144785]: run: "zfs" "recv" "-Fs" "tank/backup/zoop/gun/ROOT/arch"
Jun 09 20:53:50 arnold zoop[144785]: cannot receive new filesystem stream: incompatible embedded data stream feature with encrypted receive.
```

This is an interesting resuming send that appeared to complete, but then the next snapshot sent fails in the same way as above.
```
Jun 10 00:03:30 arnold zoop[81322]: zcopy: innerpool/ROOT/arch to tank/backup/zoop/gun/ROOT/arch
Jun 10 00:03:30 arnold zoop[81322]: run: "zfs" "list" "-pH" "-s" "name" "-o" "receive_resume_token," "-t" "filesystem" "tank/backup/zoop/gun/ROOT/arch"
Jun 10 00:03:30 arnold zoop[81322]: Resuming partial recv in tank/backup/zoop/gun/ROOT/arch
Jun 10 00:03:30 arnold zoop[81322]: run: "ssh" "gun-zxfer" "zfs" "send" "-t" "1-12f43a8be6-118-789c636064000310a500c4ec50360710e72765a526973030d47943d460c8a7a515a79630c001489e0d493ea9b224b51848275c9ec9854d7f497e7a69660ad01c865b2de23a0fd90390e439c1f27989b9a90c0c997979a9450>
Jun 10 00:03:30 arnold zoop[81322]: run: "zfs" "recv" "-Fs" "tank/backup/zoop/gun/ROOT/arch"
Jun 10 00:08:29 arnold zoop[81322]: run: "ssh" "gun-zxfer" "zfs" "list" "-pH" "-s" "name" "-o" "createtxg,name,guid,type," "-d" "1" "-t" "snapshot,bookmark" "innerpool/ROOT/arch"
Jun 10 00:08:29 arnold zoop[81322]: run: "zfs" "list" "-pH" "-s" "name" "-o" "createtxg,name,guid,type," "-d" "1" "-t" "snapshot" "tank/backup/zoop/gun/ROOT/arch"
Jun 10 00:08:29 arnold zoop[81322]: run: "ssh" "gun-zxfer" "zfs" "send" "-eLc" "-i" "innerpool/ROOT/arch@znap_2019-04-01-0400_monthly" "innerpool/ROOT/arch@znap_2019-04-22-0400_weekly"
Jun 10 00:08:29 arnold zoop[81322]: run: "zfs" "recv" "-Fs" "tank/backup/zoop/gun/ROOT/arch"
Jun 10 00:08:45 arnold zoop[81322]: cannot receive incremental stream: destination tank/backup/zoop/gun/ROOT/arch contains partially-complete state from "zfs receive -s".
Jun 10 00:08:45 arnold zoop[81322]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: StringError("send or recv failed: Some(0), Some(1)") }', src/libcore/result.rs:997:5
Jun 10 00:08:45 arnold zoop[81322]: note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Jun 10 00:08:45 arnold systemd[1]: zcopy@gun.service: Main process exited, code=exited, status=101/n/a
Jun 10 00:08:45 arnold systemd[1]: zcopy@gun.service: Failed with result 'exit-code'.
Jun 10 00:08:45 arnold systemd[1]: Failed to start zcopy@gun.service.
Jun 10 00:10:00 arnold systemd[1]: Starting zcopy@gun.service...
Jun 10 00:10:00 arnold zoop[153512]: copy from innerpool to tank/backup/zoop/gun (recursive=true)
Jun 10 00:10:00 arnold zoop[153512]: dry_run: false
Jun 10 00:10:00 arnold zoop[153512]: run: "ssh" "gun-zxfer" "zfs" "list" "-pH" "-s" "name" "-o" "name," "-r" "-t" "filesystem" "innerpool"
Jun 10 00:10:00 arnold zoop[153512]: zcopy: innerpool to tank/backup/zoop/gun
Jun 10 00:10:00 arnold zoop[153512]: run: "zfs" "list" "-pH" "-s" "name" "-o" "receive_resume_token," "-t" "filesystem" "tank/backup/zoop/gun"
Jun 10 00:10:00 arnold zoop[153512]: run: "ssh" "gun-zxfer" "zfs" "list" "-pH" "-s" "name" "-o" "createtxg,name,guid,type," "-d" "1" "-t" "snapshot,bookmark" "innerpool"
Jun 10 00:10:00 arnold zoop[153512]: run: "zfs" "list" "-pH" "-s" "name" "-o" "createtxg,name,guid,type," "-d" "1" "-t" "snapshot" "tank/backup/zoop/gun"
Jun 10 00:10:00 arnold zoop[153512]: zcopy: innerpool/ROOT to tank/backup/zoop/gun/ROOT
Jun 10 00:10:00 arnold zoop[153512]: run: "zfs" "list" "-pH" "-s" "name" "-o" "receive_resume_token," "-t" "filesystem" "tank/backup/zoop/gun/ROOT"
Jun 10 00:10:00 arnold zoop[153512]: run: "ssh" "gun-zxfer" "zfs" "list" "-pH" "-s" "name" "-o" "createtxg,name,guid,type," "-d" "1" "-t" "snapshot,bookmark" "innerpool/ROOT"
Jun 10 00:10:00 arnold zoop[153512]: run: "zfs" "list" "-pH" "-s" "name" "-o" "createtxg,name,guid,type," "-d" "1" "-t" "snapshot" "tank/backup/zoop/gun/ROOT"
Jun 10 00:10:00 arnold zoop[153512]: zcopy: innerpool/ROOT/arch to tank/backup/zoop/gun/ROOT/arch
Jun 10 00:10:00 arnold zoop[153512]: run: "zfs" "list" "-pH" "-s" "name" "-o" "receive_resume_token," "-t" "filesystem" "tank/backup/zoop/gun/ROOT/arch"
Jun 10 00:10:00 arnold zoop[153512]: Resuming partial recv in tank/backup/zoop/gun/ROOT/arch
Jun 10 00:10:00 arnold zoop[153512]: run: "ssh" "gun-zxfer" "zfs" "send" "-t" "1-166e6666c2-138-789c636064000310a501c49c50360710a715e5e7a69766a63040413ec3ad16719d87ec0a40363b92bafca4acd4e41206063e7b4eb03a0cf9b4b4e2d412908c055c9e0d493ea9b224b518489f488be4c4a6bf241fe20a574d>
Jun 10 00:10:00 arnold zoop[153512]: run: "zfs" "recv" "-Fs" "tank/backup/zoop/gun/ROOT/arch"
Jun 10 00:10:02 arnold zoop[153512]: run: "ssh" "gun-zxfer" "zfs" "list" "-pH" "-s" "name" "-o" "createtxg,name,guid,type," "-d" "1" "-t" "snapshot,bookmark" "innerpool/ROOT/arch"
Jun 10 00:10:02 arnold zoop[153512]: run: "zfs" "list" "-pH" "-s" "name" "-o" "createtxg,name,guid,type," "-d" "1" "-t" "snapshot" "tank/backup/zoop/gun/ROOT/arch"
Jun 10 00:10:02 arnold zoop[153512]: run: "ssh" "gun-zxfer" "zfs" "send" "-eLc" "-i" "innerpool/ROOT/arch@znap_2019-04-22-0400_weekly" "innerpool/ROOT/arch@znap_2019-04-29-0400_weekly"
Jun 10 00:10:02 arnold zoop[153512]: run: "zfs" "recv" "-Fs" "tank/backup/zoop/gun/ROOT/arch"
Jun 10 00:14:03 arnold zoop[153512]: cannot receive incremental stream: checksum mismatch or incomplete stream.
Jun 10 00:14:03 arnold zoop[153512]: Partially received snapshot is saved.
Jun 10 00:14:03 arnold zoop[153512]: A resuming stream can be generated on the sending system by running:
Jun 10 00:14:03 arnold zoop[153512]:     zfs send -t 1-139ab6015c-138-789c636064000310a501c49c50360710a715e5e7a69766a6304081ab26e3456fce5f4f14806c762475f94959a9c9250c0c29b682607518f26969c5a9252099798c30793624f9a4ca92d46290fd61336b19b1e82fc987b82248b021b5b3df6d9507923c2758>
Jun 10 00:14:03 arnold zoop[153512]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: StringError("send or recv failed: Some(255), Some(1)") }', src/libcore/result.rs:997:5
Jun 10 00:14:03 arnold zoop[153512]: note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Jun 10 00:14:03 arnold systemd[1]: zcopy@gun.service: Main process exited, code=exited, status=101/n/a
Jun 10 00:14:03 arnold systemd[1]: zcopy@gun.service: Failed with result 'exit-code'.
Jun 10 00:14:03 arnold systemd[1]: Failed to start zcopy@gun.service.
```

These are direct commands to attempt to resolve:
```
x@arnold ~/d/zfs $ sudo "ssh" "gun-zxfer" "zfs" "send" "-t" "1-12f43a8be6-118-789c636064000310a500c4ec50360710e72765a526973030d47943d460c8a7a515a79630c001489e0d493ea9b224b51848275c9ec9854d7f497e7a69660ad01c865b2de23a0fd90390e439c1f27989b9a90c0c997979a94505f9f939fa41fefe21fa8945c9190e55798905f146068696ba0626ba068640d2c0203e373faf2423a712e61e09a83d30ffa5e626a5a6e46783ddc18d249e9c9f5b50945a5c0c94820300e7982a0d" | sudo  "zfs" "recv" "-Fs" "tank/backup/zoop/gun/ROOT/arch"
cannot receive incremental stream: incompatible embedded data stream feature with encrypted receive.
x@arnold ~/d/zfs $ zfs list -r tank/backup/zoop -o name,receive_resume_token
NAME                                                                                                 RESUMETOK
tank/backup/zoop                                                                                     -
tank/backup/zoop/gun                                                                                 -
tank/backup/zoop/gun/ROOT                                                                            -
tank/backup/zoop/gun/ROOT/arch                                                                       1-12f43a8be6-118-789c636064000310a500c4ec50360710e72765a526973030d47943d460c8a7a515a79630c001489e0d493ea9b224b51848275c9ec9854d7f497e7a69660ad01c865b2de23a0fd90390e439c1f27989b9a90c0c997979a94505f9f939fa41fefe21fa8945c9190e55798905f146068696ba0626ba068640d2c0203e373faf2423a712e61e09a83d30ffa5e626a5a6e46783ddc18d249e9c9f5b50945a5c0c94820300e7982a0d
tank/backup/zoop/gun/ROOT/arch/var                                                                   -
x@arnold ~/d/zfs $ sudo zfs receive -A tank/backup/zoop/gun/ROOT/arch
'tank/backup/zoop/gun/ROOT/arch' does not have any resumable receive state to abort
```

**Comment by kpande** [comment]
#8819

**Comment by jmesmon** [comment]
Yes, that does match the title, and seems related. I'm not sure it covers the entire issue though. In particular, these send streams don't use `-w`, and #8819 doesn't seem to mention if abort works.

**Comment by kpande** [comment]
yes, but, provide the requested debug output from that ticket ;-)

**Comment by jmesmon** [comment]
After enabling the debug settings in https://github.com/zfsonlinux/zfs/issues/8819#issuecomment-500505301, and using "try to send the stream resume again", the dbgmsg contains this at the end:
```
1560320907   zap.c:740:fzap_checksize(): error 22
1560320907   zap_leaf.c:510:zap_entry_read_name(): error 75
1560320910   zap_leaf.c:510:zap_entry_read_name(): error 75
1560320912   zap.c:740:fzap_checksize(): error 22
1560320913   zap_leaf.c:510:zap_entry_read_name(): error 75
1560320916   zap_leaf.c:510:zap_entry_read_name(): error 75
1560320917   zap.c:740:fzap_checksize(): error 22
1560320920   zap_leaf.c:510:zap_entry_read_name(): error 75
1560320922   zap.c:740:fzap_checksize(): error 22
1560320923   zap_leaf.c:510:zap_entry_read_name(): error 75
1560320926   zap_leaf.c:510:zap_entry_read_name(): error 75
1560320927   zap.c:740:fzap_checksize(): error 22
1560320927   metaslab.c:2652:metaslab_condense(): condensing: txg 359382632, msp[406] ffffa1b33689d000, vdev id 0, spa tank, smp size 20496, segments 1277, forcing condense=FALSE
1560320929   zap_leaf.c:510:zap_entry_read_name(): error 75
1560320932   zap.c:740:fzap_checksize(): error 22
1560320932   zap_leaf.c:510:zap_entry_read_name(): error 75
```

Here's a uniq'd `grep error\ 22`:
```
 $ uniq -c <error22.log 
     44 1560321281   zap.c:740:fzap_checksize(): error 22
      1 1560321281   dnode.c:1321:dnode_hold_impl(): error 22
     65 1560321281   zap.c:740:fzap_checksize(): error 22
      1 1560321281   dmu_recv.c:640:dmu_recv_resume_begin_check(): error 22
      6 1560321281   zap.c:740:fzap_checksize(): error 22
      1 1560321284   zap.c:740:fzap_checksize(): error 22
```

**Comment by behlendorf** [comment]
@jmesmon thank you, that should help us get this debugged.

**Comment by nchevsky** [comment]
I just hit this problem when trying to receive a stream sent with `-bceLR` with no encryption on either end.

Attempting to receive the same stream on a FreeBSD host fails at the same spot but prints the correct—albeit equally hopeless—error message, _"Invalid backup stream."_

This is a full stream of an entire pool and is structured as follows:

* `root` (file system)
* `root/images` (file system)
* `root/images/disk-1` (volume) <-- `zfs receive` dies here
* `root/images/disk-2` (volume)
...
* `root/images/disk-n` (volume)

`zfs receive` successfully receives the `root` and `root/images` filesystems (about 16 GiB's worth), and fails a few seconds into the `root/images/disk-1` volume. Unfortunately, my goal in receiving this stream was to restore a backup of `root/images/disk-2`, and it looks like I'm screwed since the receive fails at the previous dataset.

Here's a cleaned-up debug log. `zfs receive` aborts around the 1569945060 mark (I suspect at `dmu_recv.c:1935:receive_read_payload_and_next_header(): error 22`).

```
1569945056   arc.c:7441:arc_tempreserve_space(): error 85
1569945056   zap.c:740:fzap_checksize(): error 22
1569945056   dmu.c:453:dmu_spill_hold_existing(): error 2
1569945056   sa.c:370:sa_attr_op(): error 2
1569945056   zfs_dir.c:1134:zfs_get_xattrdir(): error 2
1569945056   spa_checkpoint.c:167:spa_checkpoint_get_stats(): error 1026
1569945056   zap_micro.c:1590:zap_cursor_retrieve(): error 2
1569945056   zfs_ioctl.c:1103:zfs_secpolicy_log_history(): error 1
1569945056   dmu.c:453:dmu_spill_hold_existing(): error 2
1569945056   sa.c:370:sa_attr_op(): error 2
1569945056   zfs_dir.c:1134:zfs_get_xattrdir(): error 2
1569945056   zap_leaf.c:489:zap_entry_read(): error 75
1569945056   zap_leaf.c:510:zap_entry_read_name(): error 75
1569945056   zap_leaf.c:489:zap_entry_read(): error 75
1569945056   dsl_prop.c:55:dodefault(): error 2
1569945056   zap_micro.c:985:zap_lookup_impl(): error 2
1569945056   dsl_dataset.c:754:dsl_dataset_hold_flags(): error 2
1569945056   zap_micro.c:985:zap_lookup_impl(): error 2
1569945056   dsl_dataset.c:754:dsl_dataset_hold_flags(): error 2
1569945056   dsl_prop.c:55:dodefault(): error 2
1569945056   spa_checkpoint.c:167:spa_checkpoint_get_stats(): error 1026
1569945056   zfs_ioctl.c:1103:zfs_secpolicy_log_history(): error 1
...
1569945060   zvol.c:1017:zvol_get_data(): error 0
1569945060   metaslab.c:4429:metaslab_alloc(): error 28
1569945060   dmu_recv.c:1935:receive_read_payload_and_next_header(): error 22
...
1569945064   zap.c:740:fzap_checksize(): error 22
1569945064   zap_micro.c:985:zap_lookup_impl(): error 2
1569945064   dsl_prop.c:147:dsl_prop_get_dd(): error 2
...
1569945064   spa_history.c:314:spa_history_log_sync(): txg 9082 destroy temp/images/disk-1 (id 1288)
1569945064   zap_micro.c:1590:zap_cursor_retrieve(): error 2
...
1569945064   dbuf.c:2702:dbuf_findbp(): error 2
1569945064   bptree.c:232:bptree_iterate(): bptree index 0: traversing from min_txg=1 bookmark 0/0/0/0
1569945064   dsl_scan.c:3048:dsl_scan_free_block_cb(): error 85
1569945064   dsl_scan.c:3283:dsl_process_async_destroys(): freed 100000 blocks in 136ms from free_bpobj/bptree txg 9$
1569945064   zap.c:740:fzap_checksize(): error 22
1569945064   dbuf.c:2702:dbuf_findbp(): error 2
1569945064   bptree.c:232:bptree_iterate(): bptree index 0: traversing from min_txg=1 bookmark -1/1/0/160706
```

**Comment by tcaputi** [comment]
@jmesmon Would it be possible for you to provide the output of the following?
```
TOKEN="1-12f43a8be6-118-789c636064000310a500c4ec50360710e72765a526973030d47943d460c8a7a515a79630c001489e0d493ea9b224b51848275c9ec9854d7f497e7a69660ad01c865b2de23a0fd90390e439c1f27989b9a90c0c997979a94505f9f939fa41fefe21fa8945c9190e55798905f146068696ba0626ba068640d2c0203e373faf2423a712e61e09a83d30ffa5e626a5a6e46783ddc18d249e9c9f5b50945a5c0c94820300e7982a0d"
zfs send -t $TOKEN | zstreamdump
```
and 
```
TOKEN="1-12f43a8be6-118-789c636064000310a500c4ec50360710e72765a526973030d47943d460c8a7a515a79630c001489e0d493ea9b224b51848275c9ec9854d7f497e7a69660ad01c865b2de23a0fd90390e439c1f27989b9a90c0c997979a94505f9f939fa41fefe21fa8945c9190e55798905f146068696ba0626ba068640d2c0203e373faf2423a712e61e09a83d30ffa5e626a5a6e46783ddc18d249e9c9f5b50945a5c0c94820300e7982a0d"
zfs send -t $TOKEN | head -c $((8 * 40))
```
If I copied the token wrong, I apologize, but its just the token from your post above.

**Comment by jmesmon** [comment]
Unfortunately, the snapshot from which that send was based no longer exists on the sending pool, and as a result I'm unable to provide that info. Should it reoccur, I'll ensure I obtain it.

**Comment by joshenders** [comment]
> After enabling the debug settings in [#8819 (comment)](https://github.com/openzfs/zfs/issues/8819#issuecomment-500505301), and using "try to send the stream resume again", the dbgmsg contains this at the end:
> 
> ```
> 1560320907   zap.c:740:fzap_checksize(): error 22
> 1560320907   zap_leaf.c:510:zap_entry_read_name(): error 75
> 1560320910   zap_leaf.c:510:zap_entry_read_name(): error 75
> 1560320912   zap.c:740:fzap_checksize(): error 22
> 1560320913   zap_leaf.c:510:zap_entry_read_name(): error 75
> 1560320916   zap_leaf.c:510:zap_entry_read_name(): error 75
> 1560320917   zap.c:740:fzap_checksize(): error 22
> 1560320920   zap_leaf.c:510:zap_entry_read_name(): error 75
> 1560320922   zap.c:740:fzap_checksize(): error 22
> 1560320923   zap_leaf.c:510:zap_entry_read_name(): error 75
> 1560320926   zap_leaf.c:510:zap_entry_read_name(): error 75
> 1560320927   zap.c:740:fzap_checksize(): error 22
> 1560320927   metaslab.c:2652:metaslab_condense(): condensing: txg 359382632, msp[406] ffffa1b33689d000, vdev id 0, spa tank, smp size 20496, segments 1277, forcing condense=FALSE
> 1560320929   zap_leaf.c:510:zap_entry_read_name(): error 75
> 1560320932   zap.c:740:fzap_checksize(): error 22
> 1560320932   zap_leaf.c:510:zap_entry_read_name(): error 75
> ```
> 
> Here's a uniq'd `grep error\ 22`:
> 
> ```
>  $ uniq -c <error22.log 
>      44 1560321281   zap.c:740:fzap_checksize(): error 22
>       1 1560321281   dnode.c:1321:dnode_hold_impl(): error 22
>      65 1560321281   zap.c:740:fzap_checksize(): error 22
>       1 1560321281   dmu_recv.c:640:dmu_recv_resume_begin_check(): error 22
>       6 1560321281   zap.c:740:fzap_checksize(): error 22
>       1 1560321284   zap.c:740:fzap_checksize(): error 22
> ```

The issue and post that contain instructions for the debug settings is 404. I'm encountering the same issue and would like to try to debug, do you happen to recall what these debug settings were?
